### PR TITLE
Add sections for story

### PR DESCRIPTION
**Pull request by hectoruch**
Add:

- First Section component
- Title Section component.
- Effect parallax
- New styles

### CODE REVIEW

**Comment by hectoruch** [comment]
Add:

- Mesh world section component (first gallery)
- Images
- New styles

**Comment by hectoruch** [comment]
Add:

- Gallery one section component
- New styles

**Comment by hectoruch** [comment]
Add:

- Fourth section component
- Fix styles

**Comment by hectoruch** [comment]
Add:

- Gallery images two section
- New images
- New styles
- Fix some styles errors
- Add normalize file (not include on web yet)

**Comment by hectoruch** [comment]
Add:

- Cirtcles section
- New styles

**Comment by hectoruch** [comment]
Add:

- Video section
- Add video file demo
- Add logic for open and close video (WIP)
- Add styles for video and container (WIP)

**Comment by hectoruch** [comment]
Add:

- d3.js
- New logic (example) for stop and play video with scroll height.

**Comment by hectoruch** [comment]
Add:

- Bezier cubic animation.
- Functions for mousewheel component animation.
- Fix some errors on gallery functions.

**Comment by hectoruch** [comment]
Add:

- Animations for second gallery.
- Improve cubic bezier animation.

**Comment by davidsingal** [comment]
Is it ready to merge? Maybe we can add other things like visualisations in other PR.

**Comment by hectoruch** [comment]
Add:

- New styles for video player
- New library object-fit-video (IE explorer and Edge)

**Comment by hectoruch** [comment]
@davidsingal is ready to merge!

**Pull request merged**
